# Generated by Django 5.2.8 on 2025-12-11 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='customers/avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. My Prado, Office Bus', max_length=50)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('transmission_type', models.CharField(choices=[('AUTO', 'Automatic'), ('MANUAL', 'Manual')], default='AUTO', max_length=10)),
                ('vehicle_category', models.CharField(choices=[('A', 'Category A (Motorcycle)'), ('B', 'Category B (Car/Jeep)'), ('C', 'Category C (Truck)'), ('D', 'Category D (Bus)'), ('E', 'Category E (Heavy Machine/Trailer)'), ('F', 'Category F (Special)')], default='B', max_length=5)),
                ('required_license_score', models.IntegerField(default=10, editable=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='drivers/avatars/')),
                ('license_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('license_category', models.CharField(choices=[('A', 'Category A (Motorcycles)'), ('B', 'Category B (Standard Cars)'), ('C', 'Category C (Trucks)'), ('D', 'Category D (Buses)'), ('E', 'Category E (Heavy Trailers)'), ('F', 'Category F (Special Machinery)')], default='B', help_text='Highest category held by the driver', max_length=5)),
                ('license_score', models.IntegerField(default=10, help_text='Auto-calculated score for matching logic')),
                ('transmission_capability', models.CharField(choices=[('AUTO', 'Automatic Only'), ('BOTH', 'Manual & Automatic')], default='AUTO', max_length=10)),
                ('current_status', models.CharField(choices=[('OFFLINE', 'Offline'), ('AVAILABLE', 'Available'), ('BUSY', 'Busy on Ride')], default='OFFLINE', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('average_rating', models.FloatField(default=5.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(blank=True, help_text='e.g. Spouse, Parent, Friend', max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='users.customerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PreferredDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Home, Work, Gym', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_destinations', to='users.customerprofile')),
            ],
        ),
    ]
