# Generated by Django 5.2.8 on 2025-12-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customerprofile_customervehicle_driverprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='criminal_record_file',
            field=models.FileField(blank=True, help_text='Certificate of non-conviction', null=True, upload_to='drivers/criminal_records/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='driving_license_file',
            field=models.FileField(blank=True, help_text='Upload scanned copy of driving license', null=True, upload_to='drivers/licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='national_id_file',
            field=models.FileField(blank=True, help_text='Upload national ID or Passport', null=True, upload_to='drivers/ids/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='other_documents_file',
            field=models.FileField(blank=True, help_text='Any other relevant certifications', null=True, upload_to='drivers/others/'),
        ),
    ]
