# Generated by Django 5.2.8 on 2025-12-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driverprofile_criminal_record_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customervehicle',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='criminal_record_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/criminal_records/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='driving_license_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/licenses/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_category',
            field=models.CharField(choices=[('A', 'Category A (Motorcycles)'), ('B', 'Category B (Standard Cars)'), ('C', 'Category C (Trucks)'), ('D', 'Category D (Buses)'), ('E', 'Category E (Heavy Trailers)'), ('F', 'Category F (Special Machinery)')], default='B', max_length=5),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_score',
            field=models.IntegerField(default=10, help_text='Auto-calculated score'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='national_id_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/ids/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='other_documents_file',
            field=models.FileField(blank=True, null=True, upload_to='drivers/others/'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='preferreddestination',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
