# Generated by Django 5.2.8 on 2025-12-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text="If null, it's an immediate booking", null=True),
        ),
    ]
