from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, 
    UserCreationForm, 
    PasswordResetForm, 
    SetPasswordForm
)
from django.contrib.auth import get_user_model
import re
from django.core.mail import EmailMultiAlternatives
import threading
from django.template import loader
from django.template.loader import render_to_string

User = get_user_model()

# --- CREATE THE THREAD CLASS ---
class EmailThread(threading.Thread):
    def __init__(self, email_message):
        self.email_message = email_message
        threading.Thread.__init__(self)

    def run(self):
        self.email_message.send()

# --- EXISTING LOGIN FORM ---
class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Username, Email, or Phone",
        widget=forms.TextInput(attrs={
            'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-200 text-gray-900 transition duration-200 outline-none',
            'placeholder': 'e.g., john@example.com',
            'autofocus': True
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-200 text-gray-900 transition duration-200 outline-none',
            'placeholder': 'Enter your password'
        })
    )

# --- EXISTING REGISTRATION FORM ---
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
        'placeholder': 'john@example.com'
    }))
    phone_number = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
        'placeholder': '+250 7...'
    }))
    is_driver = forms.BooleanField(
        required=False, 
        label="I want to sign up as a Driver",
        widget=forms.CheckboxInput(attrs={'class': 'w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500'})
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'phone_number', 'is_driver')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
            'placeholder': 'Choose a username'
        })
        # Style the Password 1 and Password 2 fields generated by UserCreationForm
        for field in ['password1', 'password2']:
            if field in self.fields:
                self.fields[field].widget.attrs.update({
                    'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
                    'placeholder': '********'
                })
        
        self.fields["password1"].help_text = """
            <div id="pw-rules" class="hidden text-gray-600 text-sm">
                <ul class="list-disc pl-6 space-y-1">
                    <li>At least 8 characters</li>
                    <li>Not too similar to your personal info</li>
                    <li>Not a common password</li>
                    <li>Cannot be only numbers</li>
                </ul>
            </div>
        """

    def clean_phone_number(self):
        phone = self.cleaned_data.get('phone_number')
        if not phone:
            return phone
        cleaned = re.sub(r"\D", "", str(phone))
        if len(cleaned) < 10 or len(cleaned) > 15:
            raise forms.ValidationError('Phone number must contain between 10 and 15 digits.')
        return cleaned

# --- NEW PASSWORD RESET FORMS ---
class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email Address",
        widget=forms.EmailInput(attrs={
            'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
            'placeholder': 'Enter your registered email'
        })
    )

    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        """
        Override the standard send_mail method to use threads.
        """
        # Render the subject and message content
        from django.template import loader
        
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        
        body = loader.render_to_string(email_template_name, context)
        
        # Change: Use EmailMultiAlternatives instead of EmailMessage
        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        
        if html_email_template_name:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')

        # Send using the thread
        EmailThread(email_message).start()


class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Iterate over all fields (new_password1, new_password2) to apply styling
        for field in self.fields.values():
            field.widget.attrs.update({
                'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none'
            })