from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm, 
    UserCreationForm, 
    PasswordResetForm, 
    SetPasswordForm
)
from django.contrib.auth import get_user_model
import re
from django.core.mail import EmailMultiAlternatives
import threading
from django.template import loader
from django.template.loader import render_to_string
import threading
from .models import DriverProfile, CustomerProfile
from django.contrib.auth import authenticate

User = get_user_model()

# --- CREATE THE THREAD CLASS ---
class EmailThread(threading.Thread):
    def __init__(self, email_message):
        self.email_message = email_message
        threading.Thread.__init__(self)

    def run(self):
        self.email_message.send()

# --- EXISTING LOGIN FORM ---
class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Username, Email, or Phone",
        widget=forms.TextInput(attrs={
            'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-200 text-gray-900 transition duration-200 outline-none',
            'placeholder': 'e.g., john@example.com',
            'autofocus': True
        })
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:bg-white focus:ring-2 focus:ring-blue-200 text-gray-900 transition duration-200 outline-none',
            'placeholder': 'Enter your password'
        })
    )

# --- EXISTING REGISTRATION FORM ---
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={
        'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
        'placeholder': 'john@example.com'
    }))
    phone_number = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
        'placeholder': '+250 7...'
    }))
    is_driver = forms.BooleanField(
        required=False, 
        label="I want to sign up as a Driver",
        widget=forms.CheckboxInput(attrs={'class': 'w-4 h-4 text-blue-600 border-gray-300 rounded focus:ring-blue-500'})
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'phone_number', 'is_driver')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
            'placeholder': 'Choose a username'
        })
        # Style the Password 1 and Password 2 fields generated by UserCreationForm
        for field in ['password1', 'password2']:
            if field in self.fields:
                self.fields[field].widget.attrs.update({
                    'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
                    'placeholder': '********'
                })
        
        self.fields["password1"].help_text = """
            <div id="pw-rules" class="hidden text-gray-600 text-sm">
                <ul class="list-disc pl-6 space-y-1">
                    <li>At least 8 characters</li>
                    <li>Not too similar to your personal info</li>
                    <li>Not a common password</li>
                    <li>Cannot be only numbers</li>
                </ul>
            </div>
        """

    def clean_phone_number(self):
        phone = self.cleaned_data.get('phone_number')
        if not phone:
            return phone
        cleaned = re.sub(r"\D", "", str(phone))
        if len(cleaned) < 10 or len(cleaned) > 15:
            raise forms.ValidationError('Phone number must contain between 10 and 15 digits.')
        return cleaned

# --- NEW PASSWORD RESET FORMS ---
class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email Address",
        widget=forms.EmailInput(attrs={
            'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none',
            'placeholder': 'Enter your registered email'
        })
    )

    def send_mail(self, subject_template_name, email_template_name,
                  context, from_email, to_email, html_email_template_name=None):
        """
        Override the standard send_mail method to use threads.
        """
        # Render the subject and message content
        from django.template import loader
        
        subject = loader.render_to_string(subject_template_name, context)
        # Email subject *must not* contain newlines
        subject = ''.join(subject.splitlines())
        
        body = loader.render_to_string(email_template_name, context)
        
        # Change: Use EmailMultiAlternatives instead of EmailMessage
        email_message = EmailMultiAlternatives(subject, body, from_email, [to_email])
        
        if html_email_template_name:
            html_email = loader.render_to_string(html_email_template_name, context)
            email_message.attach_alternative(html_email, 'text/html')

        # Send using the thread
        EmailThread(email_message).start()


class CustomSetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Iterate over all fields (new_password1, new_password2) to apply styling
        for field in self.fields.values():
            field.widget.attrs.update({
                'class': 'w-full px-4 py-3 rounded-lg bg-gray-50 border border-gray-300 focus:border-blue-500 focus:ring-2 focus:ring-blue-200 outline-none'
            })

# --- PROFILE FORMS ---

class DriverProfileForm(forms.ModelForm):
    class Meta:
        model = DriverProfile
        fields = [
            'profile_picture', 
            'license_number', 
            'license_expiry_date', 
            'license_category', 
            'transmission_capability'
        ]
        widgets = {
            'license_expiry_date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Apply Tailwind styles to all fields
        for field_name, field in self.fields.items():
            current_classes = field.widget.attrs.get('class', '')
            
            if isinstance(field.widget, (forms.TextInput, forms.DateInput, forms.Select)):
                field.widget.attrs['class'] = f"{current_classes} bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5"
            
            elif isinstance(field.widget, forms.FileInput):
                field.widget.attrs['class'] = f"{current_classes} block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none"

class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = CustomerProfile
        fields = ['profile_picture']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.FileInput):
                field.widget.attrs['class'] = "block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none"

class DriverApplicationForm(forms.ModelForm):
    # Fields from CustomUser model for contact updates
    email = forms.EmailField(label="Email Address", required=True, widget=forms.EmailInput(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'}))
    phone_number = forms.CharField(label="Phone Number", required=True, widget=forms.TextInput(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'}))

    class Meta:
        model = DriverProfile
        fields = [
            'license_number',
            'license_expiry_date',
            'license_category',
            'transmission_capability',
            'driving_license_file',
            'national_id_file',
            'criminal_record_file',
            'other_documents_file'
        ]
        widgets = {
            'license_expiry_date': forms.DateInput(attrs={'type': 'date', 'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'}),
            'license_number': forms.TextInput(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'}),
            'license_category': forms.Select(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'}),
            'transmission_capability': forms.Select(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Pre-populate user fields
        if self.instance and self.instance.user:
            self.fields['email'].initial = self.instance.user.email
            self.fields['phone_number'].initial = self.instance.user.phone_number
        
        # Apply standard styling to file inputs
        for field_name in ['driving_license_file', 'national_id_file', 'criminal_record_file', 'other_documents_file']:
            self.fields[field_name].widget.attrs.update({
                'class': 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 dark:text-gray-400 focus:outline-none'
            })

    def save(self, commit=True):
        # Save DriverProfile fields
        driver_profile = super().save(commit=False)
        
        # Save CustomUser fields
        if driver_profile.user:
            driver_profile.user.email = self.cleaned_data['email']
            driver_profile.user.phone_number = self.cleaned_data['phone_number']
            if commit:
                driver_profile.user.save()
        
        if commit:
            driver_profile.save()
        return driver_profile
    
class SensitiveDataUpdateForm(forms.ModelForm):
    """
    Base form for updating sensitive data like email/phone.
    Requires current password to save.
    """
    current_password = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'}),
        help_text="Required to save changes."
    )

    class Meta:
        model = User
        fields = ['email', 'phone_number']

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)
        # Style fields
        for field in ['email', 'phone_number']:
            self.fields[field].widget.attrs.update({'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'})

    def clean_current_password(self):
        password = self.cleaned_data.get('current_password')
        if not self.user.check_password(password):
            raise forms.ValidationError("Incorrect password.")
        return password

class CustomerProfileUpdateForm(forms.ModelForm):
    """
    For updating non-sensitive customer profile data (e.g., Picture).
    """
    class Meta:
        model = CustomerProfile
        fields = ['profile_picture'] # Add other fields like 'preferred_name' if added to model
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['profile_picture'].widget.attrs.update({'class': 'block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50'})

class DriverSensitiveUpdateForm(SensitiveDataUpdateForm):
    """
    For drivers updating email/phone. 
    Inherits password check from SensitiveDataUpdateForm.
    """
    pass

class DriverProfileUpdateForm(forms.ModelForm):
    """
    For drivers updating documents/license.
    WARNING: Saving this will trigger re-verification logic in the view.
    """
    class Meta:
        model = DriverProfile
        fields = ['profile_picture', 'license_number', 'license_expiry_date', 'driving_license_file']
        widgets = {
            'license_expiry_date': forms.DateInput(attrs={'type': 'date'}),
        }
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Styling loop
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5'})